"""Emit a Lean module from synthesized certificates.

The generated file contains no proofs beyond `by decide`: every claim is a
finite integer computation the kernel redoes from scratch. Nothing about how the
certificate was found is trusted, or even recorded.
"""

from __future__ import annotations

from fractions import Fraction
from typing import Sequence

from .exact import Certificate, apply_int, eval_quad, quad_of_sos

HEADER = '''/-
# LyapCert.Examples

Generated by `python -m lyapcert`. Do not edit by hand: regenerate from the JSON
system definitions instead.

Each system arrives as a certificate found by an exact rational solver and is
re-checked here by kernel computation. `Valid` being `true` is what licenses
every theorem below, via `LyapCert.Quadratic`.
-/
import LyapCert

set_option autoImplicit false

namespace LyapCert
namespace Examples

'''


def _sos(terms: Sequence[tuple[int, int, int]]) -> str:
    if not terms:
        return "[]"
    return "[" + ", ".join(f"⟨{c}, {a}, {b}⟩" for c, a, b in terms) + "]"


def _ident(name: str) -> str:
    parts = "".join(ch if ch.isalnum() else " " for ch in name).split()
    if not parts:
        return "system"
    head, *rest = parts
    return head.lower() + "".join(w.capitalize() for w in rest)


def render_certificate(cert: Certificate, title: str = "", state: str = "",
                       settle: dict | None = None) -> str:
    ident = _ident(cert.name)
    (a, b), (c, d) = cert.B
    lines: list[str] = []

    doc = [f"/-- {title or cert.name}."]
    if state:
        doc.append(f"State: {state}.")
    if cert.q == 1:
        doc.append(
            f"Dynamics are integer, so the certified map is the system itself. "
            f"V decays by a factor of at most {cert.num}/{cert.den} per step, so the state "
            f"norm contracts by at most its square root, about "
            f"{float(cert.true_rate) ** 0.5:.4f}."
        )
    else:
        doc.append(
            f"The physical map is A = B/{cert.q}. What is certified below is the integer "
            f"matrix B = {cert.q}A; since V is homogeneous of degree two "
            f"(`Quad.eval_scaleVec`), V(Bᵏv) = {cert.q}^(2k) V(Aᵏv), so the envelope "
            f"below reads V(Aᵏv) ≤ ({cert.num}/{cert.den * cert.q * cert.q})^k V(v), "
            f"a per-step decay of V of about {float(cert.true_rate):.4f} and so a state-norm "
            f"contraction of about {float(cert.true_rate) ** 0.5:.4f} per step."
        )
    lines.append(" ".join(doc) + " -/")
    lines.append(
        f"def {ident} : Cert :=\n"
        f"  {{ M := ⟨{a}, {b}, {c}, {d}⟩\n"
        f"    P := {_sos(cert.P_sos)}\n"
        f"    S := {_sos(cert.S_sos)}\n"
        f"    num := {cert.num}\n"
        f"    den := {cert.den} }}\n"
    )
    lines.append(
        f"/-- The certificate checks out: the kernel verifies the decay identity,\n"
        f"the sum-of-squares weights and the rate bounds. -/\n"
        f"theorem {ident}_valid : {ident}.Valid = true := by decide\n"
    )
    lines.append(
        f"/-- Geometric envelope for every initial state and every horizon. -/\n"
        f"theorem {ident}_envelope (k : Nat) (v : Vec2) :\n"
        f"    ipow {ident}.den k * {ident}.V (iterate {ident}.M.apply k v)\n"
        f"      ≤ ipow {ident}.num k * {ident}.V v :=\n"
        f"  Cert.envelope {ident}_valid k v\n"
    )
    if cert.num <= cert.den:
        lines.append(
            f"theorem {ident}_nonexpansive : {ident}.NonExpansive = true := by decide\n"
        )
        lines.append(
            f"/-- **Certified envelope.** Any sublevel set of V is forward invariant:\n"
            f"a state that starts inside never leaves. -/\n"
            f"theorem {ident}_invariant (c : Int) (k : Nat) (v : Vec2) (hv : {ident}.V v ≤ c) :\n"
            f"    {ident}.V (iterate {ident}.M.apply k v) ≤ c :=\n"
            f"  Cert.sublevel_invariant {ident}_nonexpansive c k v hv\n"
        )
    if settle and cert.q == 1:
        v0 = (int(settle["v"][0]), int(settle["v"][1]))
        k = int(settle["k"])
        V0 = eval_quad(quad_of_sos(cert.P_sos), v0)
        bound = Fraction(cert.num, cert.den) ** k * V0
        level = int(bound) if bound == int(bound) else int(bound) + 1
        lines.append(
            f"/-- **Certified settling.** From the initial state ⟨{v0[0]}, {v0[1]}⟩, after {k}\n"
            f"steps the Lyapunov value is at most {level}. The hypothesis is a finite\n"
            f"integer comparison, so `decide` discharges it. -/\n"
            f"theorem {ident}_settles :\n"
            f"    {ident}.V (iterate {ident}.M.apply {k} ⟨{v0[0]}, {v0[1]}⟩) ≤ {level} :=\n"
            f"  Cert.settles {ident}_valid {level} {k} ⟨{v0[0]}, {v0[1]}⟩ (by decide)\n"
        )
    return "\n".join(lines)


def render_module(items: list[tuple[Certificate, dict]]) -> str:
    body = "\n".join(
        render_certificate(cert, spec.get("title", ""), spec.get("state", ""), spec.get("settle"))
        for cert, spec in items
    )
    return HEADER + body + "\nend Examples\nend LyapCert\n"


def trajectory(cert: Certificate, v0: tuple[int, int], steps: int) -> list[tuple[int, int, int]]:
    """(step, V, state) for the certified integer map, for reports and tests."""
    Q = quad_of_sos(cert.P_sos)
    v = v0
    out = []
    for k in range(steps + 1):
        out.append((k, eval_quad(Q, v), v))
        v = apply_int(cert.B, v)
    return out
