"""Emit a Lean module from a screening study.

What crosses the boundary is: the network, integer sensitivity rows, the boxes,
and exact angle vectors. Lean re-solves nothing but re-checks everything: that
the angles have zero residual, that the row reproduces the flow those angles
give, and that the screen verdict follows.
"""

from __future__ import annotations

from fractions import Fraction

from .network import (
    Network, balanced, lcm_denoms, solve_dispatch, without,
)
from .study import Screen, arg_lower, arg_upper, dot, lower, upper

HEADER = '''/-
# GridCert.Examples

Generated by `python -m gridcert`. Do not edit by hand: regenerate from the JSON
study file instead.

Every sensitivity row below is tied back to the network equations at the
dispatch that binds it, so nothing here rests on a PTDF or LODF being correct
because some other program said so.
-/
import GridCert

set_option autoImplicit false

namespace GridCert
namespace Examples

'''


def _ints(xs) -> str:
    return "[" + ", ".join(str(int(x)) for x in xs) + "]"


def _box(box) -> str:
    return "[" + ", ".join(f"⟨{lo}, {hi}⟩" for lo, hi in box) + "]"


def _net(net: Network) -> str:
    return "[" + ", ".join(f"⟨{l.src}, {l.dst}, {l.susc}⟩" for l in net.lines) + "]"


def _ident(s: str) -> str:
    parts = "".join(c if c.isalnum() else " " for c in s).split()
    head, *rest = parts
    out = head.lower() + "".join(w.capitalize() for w in rest)
    return out if out[0].isalpha() else "s" + out


def render_network(net: Network) -> str:
    names = ", ".join(f"{i}={b}" for i, b in enumerate(net.buses))
    lines = "\n".join(
        f"* line {i}: {l.name}, susceptance {l.susc}, rating {l.rating} MW"
        for i, l in enumerate(net.lines)
    )
    return (
        f"/-! ## The study network\n\n"
        f"Buses: {names}. Slack at bus {net.slack} ({net.buses[net.slack]}).\n\n"
        f"{lines}\n-/\n\n"
        f"def studyNet : Network :=\n  {_net(net)}\n"
    )


def render_screen(net: Network, sc: Screen, idx: int) -> str:
    ident = _ident(sc.label)
    K = sc.scale
    cert = sc.base
    phys = sc.network if sc.network is not None else net
    mon = phys.lines[cert.line]
    worst = sc.worst_dispatch()
    p = balanced(phys, worst)
    hi_binds = (sc.limit_mw - sc.max_flow_mw) <= (sc.min_flow_mw + sc.limit_mw)

    out: list[str] = []
    verdict = "within rating" if sc.passes else "OVERLOADED"
    lodf_note = ""
    if sc.outage is not None:
        lodf_note = (
            f"\n\nThe planner's LODF for this pair is {sc.lodf_num}/{sc.lodf_den}, but the row "
            f"certified below is the monitored branch's own sensitivity row in the network with "
            f"the branch removed, derived from that network's equations. That is stronger than "
            f"certifying an LODF-built row: it does not depend on the LODF being right."
        )
    out.append(
        f"/-! ### {sc.label} — {verdict}\n\n"
        f"Flow ranges over [{float(sc.min_flow_mw):.1f}, {float(sc.max_flow_mw):.1f}] MW against a "
        f"±{sc.limit_mw} MW rating, a margin of {float(sc.margin_mw):+.1f} MW. Row entries are the "
        f"sensitivity times {K}, so the {sc.limit_mw} MW rating is the integer {sc.limit_scaled}."
        f"{lodf_note}\n-/\n"
    )
    if sc.network is not None:
        out.append(f"/-- The study network with the outaged branch removed. -/\n"
                   f"def {ident}Net : Network :=\n  {_net(phys)}\n")
        netref = f"{ident}Net"
    else:
        netref = "studyNet"

    out.append(f"def {ident}Row : Row :=\n  {_ints(sc.row)}\n")
    out.append(f"def {ident}Box : Box :=\n  {_box(sc.box)}\n")
    out.append(f"def {ident}Limit : Int := {sc.limit_scaled}\n")
    out.append(f"theorem {ident}BoxWf : Box.Wf {ident}Box = true := by decide\n")

    angles = "[" + ",\n   ".join(_ints(a) for a in cert.angles) + "]"
    out.append(f"/-- One exact angle solution per bus: a unit injection there, withdrawn at the\n"
               f"slack, scaled by {K}. -/\n"
               f"def {ident}Angles : List Angles :=\n  {angles}\n")
    out.append(
        f"/-- **The sensitivity row is derived, not asserted.** Every entry is checked\n"
        f"against a zero-residual solution of the network equations for a unit injection at\n"
        f"that bus. Nothing here trusts an external power flow program. -/\n"
        f"theorem {ident}RowCertified :\n"
        f"    RowCertified {netref} ⟨{mon.src}, {mon.dst}, {mon.susc}⟩ {ident}Row {ident}Angles\n"
        f"      {phys.n} {phys.slack} {K} = true := by decide\n"
    )

    if sc.passes:
        out.append(
            f"theorem {ident}Screens : screen {ident}Row {ident}Box {ident}Limit = true := by decide\n"
        )
        out.append(
            f"/-- **No dispatch in the box overloads this branch.** The dispatch is\n"
            f"universally quantified, so this covers the whole operating envelope rather than\n"
            f"a list of sampled cases. -/\n"
            f"theorem {ident}Safe (q : Dispatch) (hq : Mem q {ident}Box = true) :\n"
            f"    -{ident}Limit ≤ dot {ident}Row q ∧ dot {ident}Row q ≤ {ident}Limit :=\n"
            f"  screen_sound {ident}Screens hq\n"
        )
    else:
        side = "hi" if hi_binds else "lo"
        arg = "argUpper" if hi_binds else "argLower"
        rel = (f"¬ (dot {ident}Row ({arg} {ident}Row {ident}Box) ≤ {ident}Limit)"
               if hi_binds else
               f"¬ (-{ident}Limit ≤ dot {ident}Row ({arg} {ident}Row {ident}Box))")
        out.append(
            f"/-- **This branch is overloaded, and here is the dispatch that does it.** A\n"
            f"failing screen is not a maybe: the witness lies inside the box and really does\n"
            f"exceed the rating. -/\n"
            f"theorem {ident}Violates :\n"
            f"    Mem ({arg} {ident}Row {ident}Box) {ident}Box = true ∧ {rel} :=\n"
            f"  screen_complete_{side} (by decide) {ident}BoxWf (by decide)\n"
        )
        slack_mw = p[phys.slack]
        out.append(f"/-- The binding dispatch in MW. The slack entry is whatever the box\n"
                   f"allows: its sensitivity coefficient is zero by construction, so the slack's\n"
                   f"own output cannot move this flow. Physically it absorbs {slack_mw} MW here. -/\n"
                   f"def {ident}Worst : Dispatch :=\n  {_ints(worst)}\n")
        out.append(f"theorem {ident}WorstIsBinding :\n"
                   f"    {arg} {ident}Row {ident}Box = {ident}Worst := by decide\n")
    return "\n".join(out)


def render_module(net: Network, screens: list[Screen]) -> str:
    body = render_network(net) + "\n" + "\n".join(
        render_screen(net, sc, i) for i, sc in enumerate(screens)
    )
    return HEADER + body + "\nend Examples\nend GridCert\n"
