/-
# CarbonSched.Examples

Generated by `python -m carbonsched`. Do not edit by hand: regenerate from the
JSON scenario file instead.

Each schedule arrives with a threshold found by a search that is not trusted.
`Certified` being `true` is checked here by kernel computation, and that is what
licenses the optimality theorem attached to it.
-/
import CarbonSched

set_option autoImplicit false

namespace CarbonSched
namespace Examples

/-! ### Six-hour deferrable batch process

A process that must run six hours somewhere in the day and does not care when.

Horizon 24 slots, load needs 6. Intensities in kg CO2 per MWh, allowed range [303, 561], so a forecast-free policy can promise no better than a factor of 1.85 (`online_ratio`, and tight by `online_ratio_tight`). -/

def industrialBatchProfile : Profile :=
  [498, 505, 512, 508, 496, 470, 431, 402, 371, 344, 322, 309, 303, 311, 335, 372, 418, 476, 538, 561, 547, 522, 509, 501]

def industrialBatchFeasible : Mask :=
  [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true]

def industrialBatch : Mask :=
  [false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false]

/-- The threshold certificate: every occupied slot is at or below 344,
every allowed but unoccupied slot is at or above it. -/
theorem industrialBatch_certified :
    Certified industrialBatch industrialBatchFeasible industrialBatchProfile 344 = true := by decide

/-- **Optimal.** No allowed schedule running the load for 6 slots
costs less. The rival is arbitrary, so this rules out every alternative
schedule, not just the ones some algorithm would consider. -/
theorem industrialBatch_optimal (alt : Mask) (halt : Sub alt industrialBatchFeasible = true)
    (hcount : count industrialBatch = count alt) :
    cost industrialBatch industrialBatchProfile ≤ cost alt industrialBatchProfile :=
  certified_optimal industrialBatch_certified halt hcount

theorem industrialBatch_cost : cost industrialBatch industrialBatchProfile = 1924 := by decide

def industrialBatchRunNow : Mask :=
  [true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]

/-- The run-immediately baseline is not an asserted mask: it is what
`earliest` produces from the feasibility window. -/
theorem industrialBatchRunNow_isEarliest :
    industrialBatchRunNow = earliest industrialBatchFeasible 6 := by decide

/-- Against the run now baseline: 2989 down to 1924, a saving of 1065 (35.6%). The inequality is proved;
the percentage is arithmetic on the two proved costs. -/
theorem industrialBatch_beatsRunNow :
    0 ≤ cost industrialBatchRunNow industrialBatchProfile - cost industrialBatch industrialBatchProfile :=
  savings_certified industrialBatch_certified (by decide) (by decide)

def industrialBatchNightShift : Mask :=
  [true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true]

/-- Against the night shift baseline: 3033 down to 1924, a saving of 1109 (36.6%). The inequality is proved;
the percentage is arithmetic on the two proved costs. -/
theorem industrialBatch_beatsNightShift :
    0 ≤ cost industrialBatchNightShift industrialBatchProfile - cost industrialBatch industrialBatchProfile :=
  savings_certified industrialBatch_certified (by decide) (by decide)

/-! ### Depot fleet charging inside an overnight window

Vehicles are plugged in at 18:00 and must be full by 06:00, so only the evening peak and the overnight hours are available. The optimum here is worse than the day's best hours, which is the point: the window, not the algorithm, is what limits the saving.

Horizon 24 slots, load needs 4. Intensities in kg CO2 per MWh, allowed range [501, 561], so a forecast-free policy can promise no better than a factor of 1.12 (`online_ratio`, and tight by `online_ratio_tight`). -/

def fleetChargingProfile : Profile :=
  [498, 505, 512, 508, 496, 470, 431, 402, 371, 344, 322, 309, 303, 311, 335, 372, 418, 476, 538, 561, 547, 522, 509, 501]

def fleetChargingFeasible : Mask :=
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true]

def fleetCharging : Mask :=
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, true, true]

/-- The threshold certificate: every occupied slot is at or below 538,
every allowed but unoccupied slot is at or above it. -/
theorem fleetCharging_certified :
    Certified fleetCharging fleetChargingFeasible fleetChargingProfile 538 = true := by decide

/-- **Optimal.** No allowed schedule running the load for 4 slots
costs less. The rival is arbitrary, so this rules out every alternative
schedule, not just the ones some algorithm would consider. -/
theorem fleetCharging_optimal (alt : Mask) (halt : Sub alt fleetChargingFeasible = true)
    (hcount : count fleetCharging = count alt) :
    cost fleetCharging fleetChargingProfile ≤ cost alt fleetChargingProfile :=
  certified_optimal fleetCharging_certified halt hcount

theorem fleetCharging_cost : cost fleetCharging fleetChargingProfile = 2070 := by decide

def fleetChargingChargeOnPlugIn : Mask :=
  [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false]

/-- The run-immediately baseline is not an asserted mask: it is what
`earliest` produces from the feasibility window. -/
theorem fleetChargingChargeOnPlugIn_isEarliest :
    fleetChargingChargeOnPlugIn = earliest fleetChargingFeasible 4 := by decide

/-- Against the charge on plug-in baseline: 2168 down to 2070, a saving of 98 (4.5%). The inequality is proved;
the percentage is arithmetic on the two proved costs. -/
theorem fleetCharging_beatsChargeOnPlugIn :
    0 ≤ cost fleetChargingChargeOnPlugIn fleetChargingProfile - cost fleetCharging fleetChargingProfile :=
  savings_certified fleetCharging_certified (by decide) (by decide)

/-! ### A day with no carbon signal

When intensity barely moves, the optimal schedule saves almost nothing and the ratio bound collapses toward one. Worth having in the library: a scheduler that reports large savings on a day like this is reporting a bug.

Horizon 12 slots, load needs 3. Intensities in kg CO2 per MWh, allowed range [419, 422], so a forecast-free policy can promise no better than a factor of 1.01 (`online_ratio`, and tight by `online_ratio_tight`). -/

def flatProfileProfile : Profile :=
  [420, 421, 419, 420, 422, 421, 420, 419, 421, 420, 422, 420]

def flatProfileFeasible : Mask :=
  [true, true, true, true, true, true, true, true, true, true, true, true]

def flatProfile : Mask :=
  [true, false, true, false, false, false, false, true, false, false, false, false]

/-- The threshold certificate: every occupied slot is at or below 420,
every allowed but unoccupied slot is at or above it. -/
theorem flatProfile_certified :
    Certified flatProfile flatProfileFeasible flatProfileProfile 420 = true := by decide

/-- **Optimal.** No allowed schedule running the load for 3 slots
costs less. The rival is arbitrary, so this rules out every alternative
schedule, not just the ones some algorithm would consider. -/
theorem flatProfile_optimal (alt : Mask) (halt : Sub alt flatProfileFeasible = true)
    (hcount : count flatProfile = count alt) :
    cost flatProfile flatProfileProfile ≤ cost alt flatProfileProfile :=
  certified_optimal flatProfile_certified halt hcount

theorem flatProfile_cost : cost flatProfile flatProfileProfile = 1258 := by decide

def flatProfileRunNow : Mask :=
  [true, true, true, false, false, false, false, false, false, false, false, false]

/-- The run-immediately baseline is not an asserted mask: it is what
`earliest` produces from the feasibility window. -/
theorem flatProfileRunNow_isEarliest :
    flatProfileRunNow = earliest flatProfileFeasible 3 := by decide

/-- Against the run now baseline: 1260 down to 1258, a saving of 2 (0.2%). The inequality is proved;
the percentage is arithmetic on the two proved costs. -/
theorem flatProfile_beatsRunNow :
    0 ≤ cost flatProfileRunNow flatProfileProfile - cost flatProfile flatProfileProfile :=
  savings_certified flatProfile_certified (by decide) (by decide)

end Examples
end CarbonSched
