"""JSON stack definitions, and codegen from JSON to a checkable Lean file.

The JSON is the single source of truth. `stack_to_lean` emits a Lean module
whose claims about that stack are discharged by kernel computation, so the
numbers in the Python report and the numbers the Lean kernel signs off on cannot
drift apart: they are generated from the same file.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .model import Dim, Stack, Term


def parse_stack(data: dict[str, Any]) -> tuple[Stack, int, int]:
    """Returns the stack plus its design window."""
    if data.get("units", "um") != "um":
        raise ValueError("only micrometre ('um') units are supported")
    terms = []
    for i, t in enumerate(data["terms"]):
        sign = t["sign"]
        if sign not in ("+", "-"):
            raise ValueError(f"term {i}: sign must be '+' or '-', got {sign!r}")
        dim = Dim(
            nominal=int(t["nominal"]),
            low_dev=int(t["lowDev"]),
            up_dev=int(t["upDev"]),
            label=t.get("label", f"dim{i}"),
        )
        if not dim.wf:
            raise ValueError(f"term {i} ({dim.label}): inverted tolerance band")
        terms.append(Term(sign=sign, dim=dim))
    window = data["window"]
    return Stack(terms, name=data.get("name", "stack")), int(window["lo"]), int(window["hi"])


def load_stack(path: str | Path) -> tuple[Stack, int, int]:
    return parse_stack(json.loads(Path(path).read_text()))


def _ident(name: str) -> str:
    out = "".join(c if c.isalnum() else " " for c in name).split()
    if not out:
        return "stack"
    head, *rest = out
    return head.lower() + "".join(w.capitalize() for w in rest)


def stack_to_lean(s: Stack, lo: int, hi: int, module: str | None = None) -> str:
    """Emit a Lean module asserting this stack's limits and verdict.

    Every generated claim is closed by `decide`, so `lake build` on the result is
    a kernel check of the same numbers this module reports.
    """
    ident = _ident(s.name)
    module = module or f"TolStack.Generated.{ident[0].upper()}{ident[1:]}"
    lines = [
        "/-",
        f"# {module}",
        "",
        "Generated by tolstack.io.stack_to_lean. Do not edit by hand: regenerate",
        "from the JSON stack definition instead.",
        "-/",
        "import TolStack",
        "",
        "namespace TolStack",
        "namespace Generated",
        "",
        "open Stack",
        "",
    ]
    for i, t in enumerate(s):
        lines.append(
            f'def {ident}Dim{i} : Dim :=\n'
            f'  {{ label := "{t.dim.label}", nominal := {t.dim.nominal}, '
            f"lowDev := {t.dim.low_dev}, upDev := {t.dim.up_dev} }}\n"
        )
    chain = ", ".join(
        f"⟨.{'pos' if t.sign == '+' else 'neg'}, {ident}Dim{i}⟩" for i, t in enumerate(s)
    )
    lines.append(f"def {ident} : Stack :=\n  [{chain}]\n")
    lines.append(f"theorem {ident}_wf : {ident}.Wf := by decide\n")
    lines.append(
        f"theorem {ident}_limits : {ident}.wcLo = {s.wc_lo} ∧ {ident}.wcHi = {s.wc_hi} := by decide\n"
    )
    lines.append(f"theorem {ident}_nominal : {ident}.nominal = {s.nominal} := by decide\n")
    if s.fits_within(lo, hi):
        lines.append(
            f"/-- Every assembly built from in-tolerance parts lands in [{lo}, {hi}]. -/\n"
            f"theorem {ident}_in_window {{xs : List Int}} (h : Realizes {ident} xs) :\n"
            f"    {lo} ≤ eval {ident} xs ∧ eval {ident} xs ≤ {hi} :=\n"
            f"  fitsWithin_sound (by decide) h\n"
        )
    else:
        lines.append(
            f"/-- Some in-tolerance assembly falls outside [{lo}, {hi}]. -/\n"
            f"theorem {ident}_violates_window :\n"
            f"    ∃ xs, Realizes {ident} xs ∧ ¬ ({lo} ≤ eval {ident} xs ∧ eval {ident} xs ≤ {hi}) :=\n"
            f"  fitsWithin_complete {ident}_wf (by decide)\n"
        )
    lines += ["end Generated", "end TolStack", ""]
    return "\n".join(lines)
