"""Emit a Lean module from certified schedules.

Nothing about the search is recorded or trusted. What crosses the boundary is
the mask and one integer, and Lean re-derives optimality from those.
"""

from __future__ import annotations

from typing import Sequence

from .model import Mask, Schedule, cost, count, spread

HEADER = '''/-
# CarbonSched.Examples

Generated by `python -m carbonsched`. Do not edit by hand: regenerate from the
JSON scenario file instead.

Each schedule arrives with a threshold found by a search that is not trusted.
`Certified` being `true` is checked here by kernel computation, and that is what
licenses the optimality theorem attached to it.
-/
import CarbonSched

set_option autoImplicit false

namespace CarbonSched
namespace Examples

'''


def _bools(mask: Sequence[bool]) -> str:
    return "[" + ", ".join("true" if b else "false" for b in mask) + "]"


def _ints(xs: Sequence[int]) -> str:
    return "[" + ", ".join(str(x) for x in xs) + "]"


def _ident(name: str) -> str:
    parts = "".join(ch if ch.isalnum() else " " for ch in name).split()
    if not parts:
        return "scenario"
    head, *rest = parts
    return head.lower() + "".join(w.capitalize() for w in rest)


def render_schedule(sched: Schedule, spec: dict, baselines: dict[str, Mask]) -> str:
    ident = _ident(sched.name)
    lo, hi = spread(sched.profile, sched.feasible)
    lines: list[str] = []

    title = spec.get("title", sched.name)
    unit = spec.get("unit", "kg CO₂ per slot-MWh")
    lines.append(
        f"/-! ### {title}\n\n"
        f"{spec.get('description', '')}\n\n"
        f"Horizon {len(sched.profile)} slots, load needs {sched.slots}. Intensities in "
        f"{unit}, allowed range [{lo}, {hi}], so a forecast-free policy can promise no "
        f"better than a factor of {hi / lo:.2f} (`online_ratio`, and tight by "
        f"`online_ratio_tight`). -/\n"
    )
    lines.append(f"def {ident}Profile : Profile :=\n  {_ints(sched.profile)}\n")
    lines.append(f"def {ident}Feasible : Mask :=\n  {_bools(sched.feasible)}\n")
    lines.append(f"def {ident} : Mask :=\n  {_bools(sched.mask)}\n")
    lines.append(
        f"/-- The threshold certificate: every occupied slot is at or below {sched.theta},\n"
        f"every allowed but unoccupied slot is at or above it. -/\n"
        f"theorem {ident}_certified :\n"
        f"    Certified {ident} {ident}Feasible {ident}Profile {sched.theta} = true := by decide\n"
    )
    lines.append(
        f"/-- **Optimal.** No allowed schedule running the load for {sched.slots} slots\n"
        f"costs less. The rival is arbitrary, so this rules out every alternative\n"
        f"schedule, not just the ones some algorithm would consider. -/\n"
        f"theorem {ident}_optimal (alt : Mask) (halt : Sub alt {ident}Feasible = true)\n"
        f"    (hcount : count {ident} = count alt) :\n"
        f"    cost {ident} {ident}Profile ≤ cost alt {ident}Profile :=\n"
        f"  certified_optimal {ident}_certified halt hcount\n"
    )
    lines.append(
        f"theorem {ident}_cost : cost {ident} {ident}Profile = "
        f"{cost(sched.mask, sched.profile)} := by decide\n"
    )

    for bname, bmask in baselines.items():
        bident = f"{ident}{_ident(bname)[0].upper()}{_ident(bname)[1:]}"
        bcost = cost(bmask, sched.profile)
        saved = bcost - sched.cost
        pct = 0.0 if bcost == 0 else 100.0 * saved / bcost
        lines.append(f"def {bident} : Mask :=\n  {_bools(bmask)}\n")
        if bname in ("run now", "charge on plug-in"):
            lines.append(
                f"/-- The run-immediately baseline is not an asserted mask: it is what\n"
                f"`earliest` produces from the feasibility window. -/\n"
                f"theorem {bident}_isEarliest :\n"
                f"    {bident} = earliest {ident}Feasible {sched.slots} := by decide\n"
            )
        lines.append(
            f"/-- Against the {bname} baseline: {bcost} down to "
            f"{sched.cost}, a saving of {saved} ({pct:.1f}%). The inequality is proved;\n"
            f"the percentage is arithmetic on the two proved costs. -/\n"
            f"theorem {ident}_beats{_ident(bname)[0].upper()}{_ident(bname)[1:]} :\n"
            f"    0 ≤ cost {bident} {ident}Profile - cost {ident} {ident}Profile :=\n"
            f"  savings_certified {ident}_certified (by decide) (by decide)\n"
        )
    return "\n".join(lines)


def render_module(items: list[tuple[Schedule, dict, dict[str, Mask]]]) -> str:
    body = "\n".join(render_schedule(s, spec, b) for s, spec, b in items)
    return HEADER + body + "\nend Examples\nend CarbonSched\n"
