/-
# LyapCert.Examples

Generated by `python -m lyapcert`. Do not edit by hand: regenerate from the JSON
system definitions instead.

Each system arrives as a certificate found by an exact rational solver and is
re-checked here by kernel computation. `Valid` being `true` is what licenses
every theorem below, via `LyapCert.Quadratic`.
-/
import LyapCert

set_option autoImplicit false

namespace LyapCert
namespace Examples

/-- Single-area load-frequency control loop, sampled at 0.1 s. State: frequency deviation and governor setpoint deviation. The physical map is A = B/10. What is certified below is the integer matrix B = 10A; since V is homogeneous of degree two (`Quad.eval_scaleVec`), V(Bᵏv) = 10^(2k) V(Aᵏv), so the envelope below reads V(Aᵏv) ≤ (8241/10000)^k V(v), a per-step decay of V of about 0.8241 and so a state-norm contraction of about 0.9078 per step. -/
def agc : Cert :=
  { M := ⟨8, -2, 1, 9⟩
    P := [⟨424747, 267, 10⟩, ⟨57568509392, 0, 1⟩]
    S := [⟨267, 424747, -17590⟩, ⟨11289405072, 0, 1⟩]
    num := 8241
    den := 100 }

/-- The certificate checks out: the kernel verifies the decay identity,
the sum-of-squares weights and the rate bounds. -/
theorem agc_valid : agc.Valid = true := by decide

/-- Geometric envelope for every initial state and every horizon. -/
theorem agc_envelope (k : Nat) (v : Vec2) :
    ipow agc.den k * agc.V (iterate agc.M.apply k v)
      ≤ ipow agc.num k * agc.V v :=
  Cert.envelope agc_valid k v

/-- Lossless LC exchange, quarter-period step. State: inductor current and capacitor voltage in matched units. Dynamics are integer, so the certified map is the system itself. V decays by a factor of at most 1/1 per step, so the state norm contracts by at most its square root, about 1.0000. -/
def losslessTank : Cert :=
  { M := ⟨0, -1, 1, 0⟩
    P := [⟨1, 1, 0⟩, ⟨1, 0, 1⟩]
    S := []
    num := 1
    den := 1 }

/-- The certificate checks out: the kernel verifies the decay identity,
the sum-of-squares weights and the rate bounds. -/
theorem losslessTank_valid : losslessTank.Valid = true := by decide

/-- Geometric envelope for every initial state and every horizon. -/
theorem losslessTank_envelope (k : Nat) (v : Vec2) :
    ipow losslessTank.den k * losslessTank.V (iterate losslessTank.M.apply k v)
      ≤ ipow losslessTank.num k * losslessTank.V v :=
  Cert.envelope losslessTank_valid k v

theorem losslessTank_nonexpansive : losslessTank.NonExpansive = true := by decide

/-- **Certified envelope.** Any sublevel set of V is forward invariant:
a state that starts inside never leaves. -/
theorem losslessTank_invariant (c : Int) (k : Nat) (v : Vec2) (hv : losslessTank.V v ≤ c) :
    losslessTank.V (iterate losslessTank.M.apply k v) ≤ c :=
  Cert.sublevel_invariant losslessTank_nonexpansive c k v hv

/-- **Certified settling.** From the initial state ⟨30, 40⟩, after 8
steps the Lyapunov value is at most 2500. The hypothesis is a finite
integer comparison, so `decide` discharges it. -/
theorem losslessTank_settles :
    losslessTank.V (iterate losslessTank.M.apply 8 ⟨30, 40⟩) ≤ 2500 :=
  Cert.settles losslessTank_valid 2500 8 ⟨30, 40⟩ (by decide)

/-- Two-tap deadbeat pipeline. State: current and previous sample. Dynamics are integer, so the certified map is the system itself. V decays by a factor of at most 1/2 per step, so the state norm contracts by at most its square root, about 0.7071. -/
def deadbeatPipeline : Cert :=
  { M := ⟨0, 1, 0, 0⟩
    P := [⟨1, 1, 0⟩, ⟨2, 0, 1⟩]
    S := [⟨1, 1, 0⟩]
    num := 1
    den := 2 }

/-- The certificate checks out: the kernel verifies the decay identity,
the sum-of-squares weights and the rate bounds. -/
theorem deadbeatPipeline_valid : deadbeatPipeline.Valid = true := by decide

/-- Geometric envelope for every initial state and every horizon. -/
theorem deadbeatPipeline_envelope (k : Nat) (v : Vec2) :
    ipow deadbeatPipeline.den k * deadbeatPipeline.V (iterate deadbeatPipeline.M.apply k v)
      ≤ ipow deadbeatPipeline.num k * deadbeatPipeline.V v :=
  Cert.envelope deadbeatPipeline_valid k v

theorem deadbeatPipeline_nonexpansive : deadbeatPipeline.NonExpansive = true := by decide

/-- **Certified envelope.** Any sublevel set of V is forward invariant:
a state that starts inside never leaves. -/
theorem deadbeatPipeline_invariant (c : Int) (k : Nat) (v : Vec2) (hv : deadbeatPipeline.V v ≤ c) :
    deadbeatPipeline.V (iterate deadbeatPipeline.M.apply k v) ≤ c :=
  Cert.sublevel_invariant deadbeatPipeline_nonexpansive c k v hv

/-- **Certified settling.** From the initial state ⟨12, 5⟩, after 3
steps the Lyapunov value is at most 25. The hypothesis is a finite
integer comparison, so `decide` discharges it. -/
theorem deadbeatPipeline_settles :
    deadbeatPipeline.V (iterate deadbeatPipeline.M.apply 3 ⟨12, 5⟩) ≤ 25 :=
  Cert.settles deadbeatPipeline_valid 25 3 ⟨12, 5⟩ (by decide)

end Examples
end LyapCert
