/-
# GridCert.Examples

Generated by `python -m gridcert`. Do not edit by hand: regenerate from the JSON
study file instead.

Every sensitivity row below is tied back to the network equations at the
dispatch that binds it, so nothing here rests on a PTDF or LODF being correct
because some other program said so.
-/
import GridCert

set_option autoImplicit false

namespace GridCert
namespace Examples

/-! ## The study network

Buses: 0=A, 1=B, 2=C, 3=D, 4=E. Slack at bus 0 (A).

* line 0: A-B, susceptance 36, rating 400 MW
* line 1: A-D, susceptance 33, rating 400 MW
* line 2: A-E, susceptance 156, rating 400 MW
* line 3: B-C, susceptance 93, rating 400 MW
* line 4: C-D, susceptance 34, rating 400 MW
* line 5: D-E, susceptance 34, rating 240 MW
-/

def studyNet : Network :=
  [⟨0, 1, 36⟩, ⟨0, 3, 33⟩, ⟨0, 4, 156⟩, ⟨1, 2, 93⟩, ⟨2, 3, 34⟩, ⟨3, 4, 34⟩]

/-! ### A-E base case — within rating

Flow ranges over [-227.8, 260.2] MW against a ±400 MW rating, a margin of +139.8 MW. Row entries are the sensitivity times 18523566, so the 400 MW rating is the integer 7409426400.
-/

def aEBaseCaseRow : Row :=
  [0, -2795208, -3877224, -6836856, -16432260]

def aEBaseCaseBox : Box :=
  [⟨-2000, 2000⟩, ⟨-330, -270⟩, ⟨-300, -200⟩, ⟨-400, 120⟩, ⟨0, 300⟩]

def aEBaseCaseLimit : Int := 7409426400

theorem aEBaseCaseBoxWf : Box.Wf aEBaseCaseBox = true := by decide

/-- One exact angle solution per bus: a unit injection there, withdrawn at the
slack, scaled by 18523566. -/
def aEBaseCaseAngles : List Angles :=
  [[0, 0, 0, 0, 0],
   [0, 345113, 279527, 100130, 17918],
   [0, 279527, 387731, 138890, 24854],
   [0, 100130, 138890, 244910, 43826],
   [0, 17918, 24854, 43826, 105335]]

/-- **The sensitivity row is derived, not asserted.** Every entry is checked
against a zero-residual solution of the network equations for a unit injection at
that bus. Nothing here trusts an external power flow program. -/
theorem aEBaseCaseRowCertified :
    RowCertified studyNet ⟨0, 4, 156⟩ aEBaseCaseRow aEBaseCaseAngles
      5 0 18523566 = true := by decide

theorem aEBaseCaseScreens : screen aEBaseCaseRow aEBaseCaseBox aEBaseCaseLimit = true := by decide

/-- **No dispatch in the box overloads this branch.** The dispatch is
universally quantified, so this covers the whole operating envelope rather than
a list of sampled cases. -/
theorem aEBaseCaseSafe (q : Dispatch) (hq : Mem q aEBaseCaseBox = true) :
    -aEBaseCaseLimit ≤ dot aEBaseCaseRow q ∧ dot aEBaseCaseRow q ≤ aEBaseCaseLimit :=
  screen_sound aEBaseCaseScreens hq

/-! ### A-E with D-E out — within rating

Flow ranges over [-300.0, 0.0] MW against a ±400 MW rating, a margin of +100.0 MW. Row entries are the sensitivity times 3198468, so the 400 MW rating is the integer 1279387200.

The planner's LODF for this pair is 1/1, but the row certified below is the monitored branch's own sensitivity row in the network with the branch removed, derived from that network's equations. That is stronger than certifying an LODF-built row: it does not depend on the LODF being right.
-/

/-- The study network with the outaged branch removed. -/
def aEWithDEOutNet : Network :=
  [⟨0, 1, 36⟩, ⟨0, 3, 33⟩, ⟨0, 4, 156⟩, ⟨1, 2, 93⟩, ⟨2, 3, 34⟩]

def aEWithDEOutRow : Row :=
  [0, 0, 0, 0, -3198468]

def aEWithDEOutBox : Box :=
  [⟨-2000, 2000⟩, ⟨-330, -270⟩, ⟨-300, -200⟩, ⟨-400, 120⟩, ⟨0, 300⟩]

def aEWithDEOutLimit : Int := 1279387200

theorem aEWithDEOutBoxWf : Box.Wf aEWithDEOutBox = true := by decide

/-- One exact angle solution per bus: a unit injection there, withdrawn at the
slack, scaled by 3198468. -/
def aEWithDEOutAngles : List Angles :=
  [[0, 0, 0, 0, 0],
   [0, 63726, 54002, 27404, 0],
   [0, 54002, 74906, 38012, 0],
   [0, 27404, 38012, 67028, 0],
   [0, 0, 0, 0, 20503]]

/-- **The sensitivity row is derived, not asserted.** Every entry is checked
against a zero-residual solution of the network equations for a unit injection at
that bus. Nothing here trusts an external power flow program. -/
theorem aEWithDEOutRowCertified :
    RowCertified aEWithDEOutNet ⟨0, 4, 156⟩ aEWithDEOutRow aEWithDEOutAngles
      5 0 3198468 = true := by decide

theorem aEWithDEOutScreens : screen aEWithDEOutRow aEWithDEOutBox aEWithDEOutLimit = true := by decide

/-- **No dispatch in the box overloads this branch.** The dispatch is
universally quantified, so this covers the whole operating envelope rather than
a list of sampled cases. -/
theorem aEWithDEOutSafe (q : Dispatch) (hq : Mem q aEWithDEOutBox = true) :
    -aEWithDEOutLimit ≤ dot aEWithDEOutRow q ∧ dot aEWithDEOutRow q ≤ aEWithDEOutLimit :=
  screen_sound aEWithDEOutScreens hq

/-! ### A-D base case — within rating

Flow ranges over [21.9, 307.6] MW against a ±400 MW rating, a margin of +92.4 MW. Row entries are the sensitivity times 18523566, so the 400 MW rating is the integer 7409426400.
-/

def aDBaseCaseRow : Row :=
  [0, -3304290, -4583370, -8082030, -1446258]

def aDBaseCaseBox : Box :=
  [⟨-2000, 2000⟩, ⟨-330, -270⟩, ⟨-300, -200⟩, ⟨-400, 120⟩, ⟨0, 300⟩]

def aDBaseCaseLimit : Int := 7409426400

theorem aDBaseCaseBoxWf : Box.Wf aDBaseCaseBox = true := by decide

/-- One exact angle solution per bus: a unit injection there, withdrawn at the
slack, scaled by 18523566. -/
def aDBaseCaseAngles : List Angles :=
  [[0, 0, 0, 0, 0],
   [0, 345113, 279527, 100130, 17918],
   [0, 279527, 387731, 138890, 24854],
   [0, 100130, 138890, 244910, 43826],
   [0, 17918, 24854, 43826, 105335]]

/-- **The sensitivity row is derived, not asserted.** Every entry is checked
against a zero-residual solution of the network equations for a unit injection at
that bus. Nothing here trusts an external power flow program. -/
theorem aDBaseCaseRowCertified :
    RowCertified studyNet ⟨0, 3, 33⟩ aDBaseCaseRow aDBaseCaseAngles
      5 0 18523566 = true := by decide

theorem aDBaseCaseScreens : screen aDBaseCaseRow aDBaseCaseBox aDBaseCaseLimit = true := by decide

/-- **No dispatch in the box overloads this branch.** The dispatch is
universally quantified, so this covers the whole operating envelope rather than
a list of sampled cases. -/
theorem aDBaseCaseSafe (q : Dispatch) (hq : Mem q aDBaseCaseBox = true) :
    -aDBaseCaseLimit ≤ dot aDBaseCaseRow q ∧ dot aDBaseCaseRow q ≤ aDBaseCaseLimit :=
  screen_sound aDBaseCaseScreens hq

/-! ### A-D with A-B out — OVERLOADED

Flow ranges over [160.5, 558.0] MW against a ±400 MW rating, a margin of -158.0 MW. Row entries are the sensitivity times 6099498, so the 400 MW rating is the integer 2439799200.

The planner's LODF for this pair is 1045/1929, but the row certified below is the monitored branch's own sensitivity row in the network with the branch removed, derived from that network's equations. That is stronger than certifying an LODF-built row: it does not depend on the LODF being right.
-/

/-- The study network with the outaged branch removed. -/
def aDWithABOutNet : Network :=
  [⟨0, 3, 33⟩, ⟨0, 4, 156⟩, ⟨1, 2, 93⟩, ⟨2, 3, 34⟩, ⟨3, 4, 34⟩]

def aDWithABOutRow : Row :=
  [0, -3304290, -3304290, -3304290, -591294]

def aDWithABOutBox : Box :=
  [⟨-2000, 2000⟩, ⟨-330, -270⟩, ⟨-300, -200⟩, ⟨-400, 120⟩, ⟨0, 300⟩]

def aDWithABOutLimit : Int := 2439799200

theorem aDWithABOutBoxWf : Box.Wf aDWithABOutBox = true := by decide

/-- One exact angle solution per bus: a unit injection there, withdrawn at the
slack, scaled by 6099498. -/
def aDWithABOutAngles : List Angles :=
  [[0, 0, 0, 0, 0],
   [0, 345113, 279527, 100130, 17918],
   [0, 279527, 279527, 100130, 17918],
   [0, 100130, 100130, 100130, 17918],
   [0, 17918, 17918, 17918, 35309]]

/-- **The sensitivity row is derived, not asserted.** Every entry is checked
against a zero-residual solution of the network equations for a unit injection at
that bus. Nothing here trusts an external power flow program. -/
theorem aDWithABOutRowCertified :
    RowCertified aDWithABOutNet ⟨0, 3, 33⟩ aDWithABOutRow aDWithABOutAngles
      5 0 6099498 = true := by decide

/-- **This branch is overloaded, and here is the dispatch that does it.** A
failing screen is not a maybe: the witness lies inside the box and really does
exceed the rating. -/
theorem aDWithABOutViolates :
    Mem (argUpper aDWithABOutRow aDWithABOutBox) aDWithABOutBox = true ∧ ¬ (dot aDWithABOutRow (argUpper aDWithABOutRow aDWithABOutBox) ≤ aDWithABOutLimit) :=
  screen_complete_hi (by decide) aDWithABOutBoxWf (by decide)

/-- The binding dispatch in MW. The slack entry is whatever the box
allows: its sensitivity coefficient is zero by construction, so the slack's
own output cannot move this flow. Physically it absorbs 1030 MW here. -/
def aDWithABOutWorst : Dispatch :=
  [-2000, -330, -300, -400, 0]

theorem aDWithABOutWorstIsBinding :
    argUpper aDWithABOutRow aDWithABOutBox = aDWithABOutWorst := by decide

/-! ### D-E base case — OVERLOADED

Flow ranges over [-294.1, -38.3] MW against a ±240 MW rating, a margin of -54.1 MW. Row entries are the sensitivity times 18523566, so the 240 MW rating is the integer 4445655840.
-/

def dEBaseCaseRow : Row :=
  [0, 2795208, 3877224, 6836856, -2091306]

def dEBaseCaseBox : Box :=
  [⟨-2000, 2000⟩, ⟨-330, -270⟩, ⟨-300, -200⟩, ⟨-400, 120⟩, ⟨0, 300⟩]

def dEBaseCaseLimit : Int := 4445655840

theorem dEBaseCaseBoxWf : Box.Wf dEBaseCaseBox = true := by decide

/-- One exact angle solution per bus: a unit injection there, withdrawn at the
slack, scaled by 18523566. -/
def dEBaseCaseAngles : List Angles :=
  [[0, 0, 0, 0, 0],
   [0, 345113, 279527, 100130, 17918],
   [0, 279527, 387731, 138890, 24854],
   [0, 100130, 138890, 244910, 43826],
   [0, 17918, 24854, 43826, 105335]]

/-- **The sensitivity row is derived, not asserted.** Every entry is checked
against a zero-residual solution of the network equations for a unit injection at
that bus. Nothing here trusts an external power flow program. -/
theorem dEBaseCaseRowCertified :
    RowCertified studyNet ⟨3, 4, 34⟩ dEBaseCaseRow dEBaseCaseAngles
      5 0 18523566 = true := by decide

/-- **This branch is overloaded, and here is the dispatch that does it.** A
failing screen is not a maybe: the witness lies inside the box and really does
exceed the rating. -/
theorem dEBaseCaseViolates :
    Mem (argLower dEBaseCaseRow dEBaseCaseBox) dEBaseCaseBox = true ∧ ¬ (-dEBaseCaseLimit ≤ dot dEBaseCaseRow (argLower dEBaseCaseRow dEBaseCaseBox)) :=
  screen_complete_lo (by decide) dEBaseCaseBoxWf (by decide)

/-- The binding dispatch in MW. The slack entry is whatever the box
allows: its sensitivity coefficient is zero by construction, so the slack's
own output cannot move this flow. Physically it absorbs 730 MW here. -/
def dEBaseCaseWorst : Dispatch :=
  [-2000, -330, -300, -400, 300]

theorem dEBaseCaseWorstIsBinding :
    argLower dEBaseCaseRow dEBaseCaseBox = dEBaseCaseWorst := by decide

end Examples
end GridCert
