"""JSON formula files, and codegen from JSON to a checkable Lean module.

Expression syntax in JSON:

    "V"                     a declared symbol
    "1"                     a dimensionless constant
    ["mul", e, e]           also "div", "add", "sub"
    ["pow", e, n]           integer exponent
    ["sqrt", e]
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from . import units as u
from .dimension import Dimension
from .expr import BinOp, Const, Equation, Expr, Pow, Sqrt, Sym

BINOPS = {"mul", "div", "add", "sub"}


def parse_expr(node: Any, symbols: dict[str, Dimension]) -> Expr:
    if isinstance(node, str):
        if node == "1":
            return Const()
        if node not in symbols:
            raise ValueError(f"undeclared symbol {node!r}")
        return Sym(node, symbols[node])
    if not isinstance(node, list) or not node:
        raise ValueError(f"malformed expression: {node!r}")
    op = node[0]
    if op in BINOPS:
        if len(node) != 3:
            raise ValueError(f"{op} takes two arguments: {node!r}")
        return BinOp(op, parse_expr(node[1], symbols), parse_expr(node[2], symbols))
    if op == "pow":
        if len(node) != 3 or not isinstance(node[2], int):
            raise ValueError(f"pow takes an expression and an integer: {node!r}")
        return Pow(parse_expr(node[1], symbols), node[2])
    if op == "sqrt":
        if len(node) != 2:
            raise ValueError(f"sqrt takes one argument: {node!r}")
        return Sqrt(parse_expr(node[1], symbols))
    raise ValueError(f"unknown operator {op!r}")


def parse_file(data: dict[str, Any]) -> list[Equation]:
    symbols: dict[str, Dimension] = {}
    for name, unit in data.get("symbols", {}).items():
        if unit not in u.BY_NAME:
            raise ValueError(f"symbol {name!r}: unknown unit {unit!r}")
        symbols[name] = u.BY_NAME[unit]
    out = []
    for f in data["formulas"]:
        out.append(
            Equation(f["name"], parse_expr(f["lhs"], symbols), parse_expr(f["rhs"], symbols))
        )
    return out


def load_formulas(path: str | Path) -> list[Equation]:
    return parse_file(json.loads(Path(path).read_text()))


def _lean_expr(e: Expr) -> str:
    if isinstance(e, Sym):
        return f'(.sym "{e.name}" {e.dim.to_lean()})'
    if isinstance(e, Const):
        return ".const"
    if isinstance(e, Pow):
        return f"(.pow {_lean_expr(e.base)} {e.n})"
    if isinstance(e, Sqrt):
        return f"(.sqrt {_lean_expr(e.arg)})"
    return f"(.{e.op} {_lean_expr(e.left)} {_lean_expr(e.right)})"


def _ident(name: str, i: int) -> str:
    keep = "".join(c if c.isalnum() else " " for c in name).split()
    if not keep:
        return f"formula{i}"
    head, *rest = keep
    ident = head.lower() + "".join(w.capitalize() for w in rest)
    return ident if ident[0].isalpha() else f"formula{i}"


def formulas_to_lean(eqs: list[Equation], module: str = "DimCert.Generated") -> str:
    """Emit a Lean module whose verdicts are discharged by kernel computation."""
    lines = [
        "/-",
        f"# {module}",
        "",
        "Generated by dimcert.io.formulas_to_lean. Do not edit by hand:",
        "regenerate from the JSON formula file instead.",
        "-/",
        "import DimCert",
        "",
        "set_option autoImplicit false",
        "",
        "namespace DimCert",
        "namespace Generated",
        "",
    ]
    for i, q in enumerate(eqs):
        ident = _ident(q.name, i)
        lines.append(
            f'def {ident} : Equation :=\n'
            f'  ⟨"{q.name}", {_lean_expr(q.lhs)}, {_lean_expr(q.rhs)}⟩\n'
        )
        verdict = "true" if q.checks else "false"
        lines.append(f"theorem {ident}_checks : {ident}.checks = {verdict} := by decide\n")
    lines += ["end Generated", "end DimCert", ""]
    return "\n".join(lines)
